# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4947fb31338eb75215c6b0340e848dd19e26d0048050270cf8780640295b9e8d67452c133861d0eabed72392df3d82c9e2ae198302b3323832556206c624014

test:
  secret_key_base: 8dfb435706beb268de9210821a0dca2b33934e59e5cbc21999e051e3488a6f54cf395bbc9efcf54076d8fa299f92bb4669b67a27d24fd030bdb68512e46efef5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
